repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '1.2'
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ["--with", "dev", "-f", "requirements.txt", "-o", "requirements.txt"]
